language: python
python:
  - "2.7"
  - "3.6"
sudo: required
dist: bionic
compiler:
  - gcc
# - clang
env:
  global:
    - secure: "SnIBG/xLIHX3CSvUbqqsX8xTVqIqQ7fFS6HWO6KZQVBsT6yugTwYHbyhNiU531JejYJ/I3ZrDhXfYH3qFZiYxnH1sifvwV+fnTtMXpPN7qPZwIymkjcmm6gJF51e0C7VOfUbvKFv0ngwj+ul21rgZSMuoEvxPK0WxtE3/ZSfn9c="
    - APT_DEPENDENCIES="doxygen libeigen3-dev libboost-test-dev libboost-python-dev libeigen3-dev"
    - DEBSIGN_KEYID=5AE5CD75
    - CC=gcc
    - DO_COVERAGE_ON_BRANCH="master;release"
    - DO_CPPCHECK_ON_BRANCH=""
    - DO_INSTALL_DOC_EXCEPT_ON_BRANCH=""
  matrix:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug
notifications:
  email:
    - pinocchio-build@laas.fr
branches:
  only:
    - master
    - debian
    - devel
before_install: ./.travis/run before_install
install: pip install coveralls numpy
script:
  - export CMAKE_ADDITIONAL_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILDTYPE}"
  - sudo free -m -t
  - ./.travis/run ../travis_custom/custom_build
after_failure: ./.travis/run after_failure
after_success: ./.travis/run after_success
